cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"

brew "curl"
brew "git"
brew "git-delta"
brew "node"
brew "nvm"
brew "tldr"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "lazydocker"
brew "translate-shell"
brew "romkatv/powerlevel10k/powerlevel10k"

cask "google-chrome"
cask "firefox-developer-edition"
cask "discord"
cask "docker"
cask "flux"
cask "spotify"
cask "iterm2"
cask "slack"
cask "licecap"
cask "insomnia"
cask "nordvpn"
cask "visual-studio-code"
cask "google-cloud-sdk"